#!/bin/bash

dir="$(dirname "$0")"
PACKAGES="$dir/data/base.list"

# Install base apps
function check {
    show_info "Installing base apps..."
    for package in $(cat $PACKAGES)
    do
    PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $package|grep "install ok installed")
    if [ "" == "$PKGCHECK" ]; then
        show_info "This script makes use of '$package' and it is not present on your system."
        show_info "Installing '$package'."
        show_warning 'Requires root privileges'
        sudo apt-get --force-yes -y install $package
        show_success 'Installing '$package': COMPLETE'
    else
        show_info "'$package' is installed. Proceeding"
    fi
    done
}
