#!/bin/bash

dir="$(dirname "$0")"
PURGED="$dir/data/purge.list"

function unused {
    show_info 'Removing unused applications...'
    show_warning 'Requires root privileges'
    # Feel free to change the contents of 'utilities.list' in the data folder to whatever suits your preference.
    sudo apt-get remove -y $(cat $PURGED)
    show_success 'Removing unused applications: COMPLETE'
}

# Remove old kernels
function kernels {
  show_info 'Removing outdated kernel(s)...'
  show_warning 'Requires root privileges'
  sudo dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | grep -v linux-libc-dev | xargs sudo apt-get -y purge
  show_success 'Removing outdated kernel(s): COMPLETE'
}

# Remove Orphaned Packages
function orphaned {
    show_info 'Removing orphaned packages...'
    show_warning 'Requires root privileges'
    sudo apt-get autoremove -y
    show_success 'Removing orphaned packages: COMPLETE'
}

function leftovers {
    show_info 'Removing leftover configuration files...'
    show_warning 'Requires root privileges'
    sudo dpkg --purge $(COLUMNS=200 dpkg -l | grep '^rc' | tr -s ' ' | cut -d ' ' -f 2)
    show_success 'Removing leftover configuration files: COMPLETE'
}

function clean-cache {
    show_info 'Cleaning package cache...'
    show_warning 'Requires root privileges'
    sudo apt-get clean
    show_success 'Cleaning package cache: COMPLETE'
}

# Cleanup System
function cleanup {
  kernels
  unused
  orphaned
  leftovers
  clean-cache
}
