#!/bin/bash

dir="$(dirname "$0")"

DEVTOOLS="$dir/data/development.list"

# Install Development Applications
function development {
  show_info "Installing development applications"
  sudo apt-get install -y -qq $(cat $DEVTOOLS)
  show_success "Installing development applications. Complete."
}
