#!/bin/bash

dir="$(dirname "$0")"
FAVS="$dir/data/favourites.list"

# Install Favourite Applications
function favourites {
  show_info "Installing Favourites"
  for package in $(cat $FAVS)
  do
    PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $package|grep "install ok installed")
    if [ "" == "$PKGCHECK" ]; then
        show_info "Installing '$package'."
        sudo apt-get install -y -qq --no-install-recommends $package
        show_success 'Installing '$package': COMPLETE'
    else
        show_info "'$package' is already installed"
    fi
  done
  show_success "Installing Favourites: COMPLETE."
}
