#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party/atom
source $dir/functions/third-party/dropbox
source $dir/functions/third-party/birdie
source $dir/functions/third-party/gnome
source $dir/functions/third-party/google-chrome
source $dir/functions/third-party/nvm
source $dir/functions/third-party/oracle-java
source $dir/functions/third-party/rvm
source $dir/functions/third-party/slack
source $dir/functions/third-party/solarized
source $dir/functions/third-party/steam
source $dir/functions/third-party/sublime-text3

THIRDPARTY="$dir/data/thirdparty.list"

# Install Third-Party Applications
function thirdparty {
  show_info "Installing third party apps"
  for application in $(cat $THIRDPARTY)
  do
    if [[ ${application:0:1} != '#' ]]; then
      show_info "Installing '$application'."
      show_warning 'Requires root privileges'
      eval ${application}
      show_success "$application: COMPLETE"
    fi
  done
  show_success "Installing third party apps: COMPLETE."
 }
