#!/bin/bash

# Perform system upgrade
function update {
  show_info 'Updating repository information...'
  show_warning 'Requires root privileges'
  sudo apt-get update -qq
  show_success 'Done.'
  # Dist-Upgrade
  show_info 'Performing system update...'
  sudo apt-get dist-upgrade -y
  # Done
  show_success 'System Update: Complete.'
}
