#!/bin/bash

dir="$(dirname "$0")"
UTILS="$dir/data/utilities.list"

function utilities {
  show_info "Installing Utilities"
  for package in $(cat $UTILS)
  do
    PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $package|grep "install ok installed")
    if [ "" == "$PKGCHECK" ]; then
        show_info "Installing '$package'."
        sudo apt-get --force-yes -y install $package
        show_success 'Installing '$package': COMPLETE'
    else
        show_info "'$package' is already installed"
    fi
  done
  show_success "Installing Utilities: COMPLETE."
}
